### ISSUE TITLE
How to get Alex token?

### ISSUE THREAD

**Issue by zairullahdev** [AyushSehrawat/leafy-bot#11]

**Comment by BenitzCoding** [comment]
What?

**Comment by AyushSehrawat** [comment]
https://github.com/AlexFlipnote
https://alexflipnote.dev

It looks like the api is no more , but another different api has come and the previous API is open source. See his github for its source code

Also, leafy-bot is very old discord.py code, so remember to update it.
@zairullahdev

**Comment by AyushSehrawat** [comment]
Well see this, ig it is still functional upto some extent
https://api.alexflipnote.dev/

**Comment by BenitzCoding** [comment]
@zairullahdev iirc, it's `nice_token_you_got_here`, It works for my project...
