### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by Aayush2005** [AyushSehrawat/leafy-bot#12]
Extension 'cogs.aki' raised an error: ModuleNotFoundError: No module named 'akinator.async_aki'

**Comment by AyushSehrawat** [comment]
Did you install the dependencies? 

Try this : https://libraries.io/pypi/akinator.py/5.0.0

```
pip uninstall akinator.py==4.0.1
```

Then instal as guided in the above link... 

If issue occurs inform me here

**Comment by Aayush2005** [comment]
I did , actually when I run the command 'pip install akinator.py' , It installs versions: 0.1.1, 0.2.0, 0.2.1 , If I tried running command for installing the recommended version , It raises error " Could not find a version that satisfies the requirement akinator.py==4.0.1 (from versions: 0.1.1, 0.2.0, 0.2.1)"

**Comment by AyushSehrawat** [comment]
Try with some previous version probably.. pip uninstall and try one of the version it says... If it doesn't work still then probs you need to make your own wrapper

**Comment by AyushSehrawat** [comment]
Closing this issue.. If you get any issues or want to contribute, feel free to create an issue!
